# Generated by Django 6.0.4 on 2026-04-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
